#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀 Running build before push..."

yarn build

if [ $? -ne 0 ]; then
  echo "❌ Build failed. Push aborted."
  exit 1
fi

echo "✅ Build passed. Pushing..."